### ISSUE TITLE
Dead Links (OSOE-182)

### ISSUE THREAD

**Issue by sarahelsaig** [Lombiq/Orchard-Dojo-Library#11]
Seems like the O1 documentation links are broken?

## Examples

in https://orcharddojo.net/orchard-resources/Library/Wiki/Core instead of
https://docs.orchardproject.net/projects/O1/en/latest/Documentation/Builtin-Features#Coremodules
should be 
https://docs.orchardproject.net/en/latest/Documentation/Builtin-Features/#core-modules

in https://orcharddojo.net/orchard-resources/Library/Wiki/Handler instead of
http://docs.orchardproject.net/Documentation/Understanding-content-handlers
should be 
https://docs.orchardproject.net/en/latest/Documentation/Understanding-content-handlers/

**Comment by Piedone** [comment]
Wonderful. All the docs.orchardproject.net links need to be checked.

**Comment by sarahelsaig** [comment]
https://github.com/textlint-rule/textlint-rule-no-dead-link might be of help, if docs.orchardproject.net doesn't have flood protection like GitHub.
